name: Python package

on: [push]

jobs:
  build:

    runs-on: keyiz/garnet-flow
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        git submodule init
        git submodule update
        python -m pip install --upgrade pip
        pip install -r deps/garnet/requirements.txt
        pip install deps/*.whl
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
